// Generated by Dartform — do not edit manually.
// To regenerate: Quick Actions → Generate Flutter Layer

import 'package:shopwave_backend_client/shopwave_backend_client.dart';
import '../result.dart';

/// Repository interface for [Greeting] operations.
///
/// All methods return [Result<T>] — handle both [Success] and [Failure]
/// in your state management layer (Bloc, Riverpod, Provider, GetX, etc).
abstract class GreetingRepository {
  Future<Result<Greeting>> hello(String name);
}
