// Generated by Dartform — do not edit manually.
// To regenerate: Quick Actions → Generate Flutter Layer

import 'package:shopwave_backend_client/shopwave_backend_client.dart';

/// Thin wrapper over the Serverpod-generated [Client.greeting] endpoint.
///
/// Responsibility: make the network call. Nothing else.
/// Business logic (error handling, retry, caching) belongs in
/// [GreetingRepositoryImpl].
class GreetingRemoteDataSource {
  final Client _client;

  const GreetingRemoteDataSource({required Client client})
      : _client = client;
  /// Calls [client.greeting.hello] directly.
  /// No business logic here — that belongs in [GreetingRepositoryImpl].
  Future<Greeting> hello(String name) =>
      _client.greeting.hello(name);
}
