// Generated by Dartform — do not edit manually.
// To regenerate: Quick Actions → Generate Flutter Layer

import 'dart:io';
import 'package:shopwave_backend_client/shopwave_backend_client.dart';
import 'greeting_remote_data_source.dart';
import 'greeting_repository.dart';
import '../result.dart';

class GreetingRepositoryImpl implements GreetingRepository {
  final GreetingRemoteDataSource _remoteDataSource;

  /// Maximum number of retry attempts for network failures.
  /// Server-side validation errors (ServerpodClientException) are NOT retried
  /// since retrying will produce the same error.
  final int _maxRetries;

  const GreetingRepositoryImpl({
    required GreetingRemoteDataSource remoteDataSource,
    int maxRetries = 2,
  })  : _remoteDataSource = remoteDataSource,
        _maxRetries = maxRetries;

  /// Exponential backoff delay for retry attempts.
  Duration _retryDelay(int attempt) =>
      Duration(milliseconds: 300 * (attempt + 1));

  /// Hello with automatic retry on network failure.
  ///
  /// Returns [Failure] immediately on server-side validation errors
  /// (these come from GreetingException on the server and won't
  /// succeed on retry).
  @override
  Future<Result<Greeting>> hello(String name) async {
    for (var attempt = 0; attempt <= _maxRetries; attempt++) {
      try {
        // TODO: Add cache check here before making network call
        // e.g. final cached = await _cache.get('greeting_hello');
        // if (cached != null) return Success(cached);

        final data = await _remoteDataSource.hello(name);

        // TODO: Cache successful response here
        // e.g. await _cache.set('greeting_hello', data);

        return Success(data);
      } on ServerpodClientException catch (e) {
        // Server-side GreetingException — do not retry, return immediately.
        // The message comes directly from the server exception.
        return Failure(e.message, exception: e);
      } on SocketException catch (e) {
        if (attempt < _maxRetries) {
          await Future<void>.delayed(_retryDelay(attempt));
          continue;
        }
        return Failure(
          'No internet connection. Please check your network and try again.',
          exception: e,
        );
      } catch (e) {
        return Failure(
          'An unexpected error occurred. Please try again.',
          exception: e,
        );
      }
    }
  }
}
